/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Platform */

#ifndef _Included_javax_microedition_m3g_Platform
#define _Included_javax_microedition_m3g_Platform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_m3g_Platform
 * Method:    finalizeInterface
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Platform_finalizeInterface
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Platform
 * Method:    _finalizeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Platform__1finalizeObject
  (JNIEnv *, jclass, jlong);

//k: Add, load EGL/OpenGL
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_Platform__1initGL
  (JNIEnv *, jclass, jint);
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Platform__1shutdownGL
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
