Document: cvm
Title: Debian cvm Manual
Author: <insert document author here>
Abstract: This manual describes what cvm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cvm/cvm.sgml.gz

Format: postscript
Files: /usr/share/doc/cvm/cvm.ps.gz

Format: text
Files: /usr/share/doc/cvm/cvm.text.gz

Format: HTML
Index: /usr/share/doc/cvm/html/index.html
Files: /usr/share/doc/cvm/html/*.html


