#! /bin/sh

case "$1" in
    configure)
        chmod a+rwx /opt/phoneme
        chmod a+rwx /opt/phoneme/bin
        chmod a+rwx /opt/phoneme/legal
        chmod a+rwx /opt/phoneme/lib
        chmod a+rwx /opt/phoneme/midp
        chmod a+rwx /opt/phoneme/midp/midp_linux_fb_gcc
        chmod a+rwx /opt/phoneme/midp/midp_linux_fb_gcc/appdb
        chmod a+rwx /opt/phoneme/midp/midp_linux_fb_gcc/bin
        chmod a+rwx /opt/phoneme/midp/midp_linux_fb_gcc/lib

        chmod a+rwx /opt/phoneme/*.sh
        chmod a+rw /opt/phoneme/*

        if test -x /usr/bin/update-mime-database; then
            update-mime-database /usr/share/mime
        fi
        if test -x /usr/bin/update-desktop-database; then
            update-desktop-database /usr/share/applications
        fi
        if test -x /usr/bin/hildon-update-category-database; then
            hildon-update-category-database /usr/share/mime
        fi
        if test -x /usr/bin/gtk-update-icon-cache; then
            /usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/hicolor
        fi
        ;;
esac
