#! /bin/sh

case "$1" in
    remove)
        if test -x /usr/bin/update-mime-database; then
            update-mime-database /usr/share/mime
        fi
        if test -x /usr/bin/update-desktop-database; then
            update-desktop-database /usr/share/applications
        fi
        if test -x /usr/bin/hildon-update-category-database; then
            hildon-update-category-database /usr/share/mime
        fi
        if test -x /usr/bin/gtk-update-icon-cache; then
            /usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/hicolor
        fi
        ;;
esac


